/**
 * Generates rs/cs2/CommandSignatures.ts: what each CS2 command pops and pushes, by stack, for
 * one revision. Source: zwyz/osrs-cache (MIT), data/commands/*.txt and the type list in
 * src/main/java/osrs/unpack/Type.java. Lines tagged with a revision override older ones.
 *
 *   npx tsx scripts/cache/generate-command-signatures.ts <osrs-cache checkout> <revision>
 */
import fs from "fs";
import path from "path";

const [root, revisionArg] = process.argv.slice(2);
if (!root || !revisionArg) {
    console.error("usage: generate-command-signatures.ts <osrs-cache checkout> <revision>");
    process.exit(1);
}
const revision = Number(revisionArg);

// Type name -> stack. Types are int-stack unless Type.java says long or string; arrays (rev 231+)
// live on the object stack, which this VM shares with strings.
const typeSource = fs.readFileSync(path.join(root, "src/main/java/osrs/unpack/Type.java"), "utf8");
const stackOf = new Map<string, string>();
for (const [, name, base] of typeSource.matchAll(/new Type\("([a-z_0-9]+)",\s*BaseVarType\.([A-Z]+)/g)) {
    stackOf.set(name, base === "LONG" ? "l" : base === "STRING" ? "s" : "i");
}
const DYNAMIC = new Set(["unknown", "argument_list"]);
function stack(type: string): string {
    if (DYNAMIC.has(type)) return "?";
    if (type === "unknown_int") return "i";
    if (type === "unknown_long") return "l";
    if (type.endsWith("array")) return "s";
    return stackOf.get(type) ?? "i";
}

const LINE = /^(\d+) \[command,([a-z0-9_]+)\](?:\(([^)]*)\))?(?:\(([^)]*)\))?(?: (\d+))?$/;
const commands = new Map<number, { name: string; inputs: string; outputs: string; version: number }>();
const dir = path.join(root, "data/commands");
for (const file of fs.readdirSync(dir).sort()) {
    for (const raw of fs.readFileSync(path.join(dir, file), "utf8").split("\n")) {
        const line = raw.trim();
        if (!line || line.startsWith("//") || line.includes("(gap)")) continue;
        const match = LINE.exec(line);
        if (!match) continue;
        const [, id, name, args, returns, versionText] = match;
        const version = versionText ? Number(versionText) : 0;
        if (version > revision) continue;
        const opcode = Number(id);
        const previous = commands.get(opcode);
        if (previous && previous.version > version) continue;
        // No parentheses: a core instruction whose stack effect depends on its operand.
        const typed = line.includes("(");
        const inputs = !typed ? "?" : (args ?? "").split(",").map((a) => a.trim().split(/\s+/)[0]).filter(Boolean).map(stack).join("");
        const outputs = !typed ? "?" : (returns ?? "").split(",").map((r) => r.trim()).filter(Boolean).map(stack).join("");
        commands.set(opcode, { name, inputs, outputs, version });
    }
}

const rows = [...commands.entries()].sort(([a], [b]) => a - b)
    .map(([opcode, c]) => `    ${opcode}: ["${c.name}", "${c.inputs}", "${c.outputs}"],`);
const out = `// Generated by scripts/cache/generate-command-signatures.ts for revision ${revision}; do not edit.
// From zwyz/osrs-cache (data/commands), Copyright 2024 zwyz, MIT licence.
/**
 * Each CS2 command's name, then the stacks it pops (in pop order reversed: as written) and pushes:
 * i int, l long, s string or array (the object stack). "?" means it depends on the operand or
 * on the script (core instructions, any-type arguments, listener argument lists).
 */
export const COMMAND_SIGNATURES_REVISION = ${revision};

export const COMMAND_SIGNATURES: Record<number, [name: string, inputs: string, outputs: string]> = {
${rows.join("\n")}
};
`;
fs.writeFileSync(path.join(__dirname, "../../rs/cs2/CommandSignatures.ts"), out);
console.log(`${commands.size} commands for revision ${revision}`);
